=== heaths/azure-sdk-tools/tools/apiview/parsers/apiview-treestyle-parser-schema/CodeFile.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "CodeFile.json",
    "type": "object",
    "properties": {
        "PackageName": {
            "type": "string"
        },
        "PackageVersion": {
            "type": "string"
        },
        "ParserVersion": {
            "type": "string",
            "description": "version of the APIview language parser used to create token file"
        },
        "Language": {
            "anyOf": [
                {
                    "type": "string",
                    "const": "C"
                },
                {
                    "type": "string",
                    "const": "C++"
                },
                {
                    "type": "string",
                    "const": "C#"
                },
                {
                    "type": "string",
                    "const": "Go"
                },
                {
                    "type": "string",
                    "const": "Java"
                },
                {
                    "type": "string",
                    "const": "JavaScript"
                },
                {
                    "type": "string",
                    "const": "Kotlin"
                },
                {
                    "type": "string",
                    "const": "Python"
                },
                {
                    "type": "string",
                    "const": "Swagger"
                },
                {
                    "type": "string",
                    "const": "Swift"
                },
                {
                    "type": "string",
                    "const": "TypeSpec"
                }
            ]
        },
        "LanguageVariant": {
            "anyOf": [
                {
                    "type": "string",
                    "const": "None"
                },
                {
                    "type": "string",
                    "const": "Spring"
                },
                {
                    "type": "string",
                    "const": "Android"
                }
            ],
            "default": "None",
            "description": "Language variant is applicable only for java variants"
        },
        "CrossLanguageMetadata": {
            "$ref": "#/$defs/CrossLanguageMetadata",
            "description": "Metadata for different languages generated from the same TypeSpec specification."
        },
        "ReviewLines": {
            "type": "array",
            "items": {
                "$ref": "#/$defs/ReviewLine"
            }
        },
        "Diagnostics": {
            "type": "array",
            "items": {
                "$ref": "#/$defs/CodeDiagnostic"
            },
            "description": "Add any system generated comments. Each comment is linked to review line ID"
        },
        "Navigation": {
            "type": "array",
            "items": {
                "$ref": "#/$defs/NavigationItem"
            },
            "description": "Navigation items are used to create a tree view in the navigation panel. Each navigation item is linked to a review line ID. This is optional.\nIf navigation items are not provided then navigation panel will be automatically generated using the review lines. Navigation items should be provided only if you want to customize the navigation panel."
        }
    },
    "required": [
        "PackageName",
        "PackageVersion",
        "ParserVersion",
        "Language",
        "ReviewLines"
    ],
    "description": "ReviewFile represents entire API review object. This will be processed to render review lines.",
    "$defs": {
        "CrossLanguageMetadata": {
            "type": "object",
            "properties": {
                "CrossLanguagePackageId": {
                    "type": "string"
                },
                "CrossLanguageDefinitionId": {
                    "$ref": "#/$defs/LanguageIdMap"
                },
                "CrossLanguageVersion": {
                    "type": "string"
                }
            },
            "required": [
                "CrossLanguagePackageId",
                "CrossLanguageDefinitionId"
            ]
        },
        "ReviewLine": {
            "type": "object",
            "properties": {
                "LineId": {
                    "type": "string",
                    "description": "lineId is only required if we need to support commenting on a line that contains this token. \nUsually code line for documentation or just punctuation is not required to have lineId. lineId should be a unique value within \nthe review token file to use it assign to review comments as well as navigation Id within the review page.\nfor e.g Azure.Core.HttpHeader.Common, azure.template.template_main"
                },
                "CrossLanguageId": {
                    "type": "string",
                    "description": "Id to identify related lines across languages based on typespec specification"
                },
                "Tokens": {
                    "type": "array",
                    "items": {
                        "$ref": "#/$defs/ReviewToken"
                    },
                    "description": "list of tokens that constructs a line in API review"
                },
                "Children": {
                    "type": "array",
                    "items": {
                        "$ref": "#/$defs/ReviewLine"
                    },
                    "description": "Add any child lines as children. For e.g. all classes and namespace level methods are added as a children of namespace(module) level code line. \nSimilarly all method level code lines are added as children of it's class code line."
                },
                "IsHidden": {
                    "type": "boolean",
                    "description": "Set current line as hidden code line by default. .NET has hidden APIs and architects don't want to see them by default."
                },
                "IsContextEndLine": {
                    "type": "boolean",
                    "description": "Set current line as context end line. For e.g. line with token } or empty line after the class or function/method to mark end of context."
                },
                "RelatedToLine": {
                    "type": "string",
                    "description": "Set ID of related line to ensure current line is not visible when a related line is hidden.\nOne e.g. is a code line for class attribute that should set class line's Line ID as related line ID.\nOR a method line decorator that should set method's line ID as related line ID."
                }
            },
            "required": [
                "Tokens"
            ],
            "description": "ReviewLine object corresponds to each line displayed on API review. If an empty line is required then add a code line object without any token."
        },
        "CodeDiagnostic": {
            "type": "object",
            "properties": {
                "DiagnosticId": {
                    "type": "string",
                    "description": "Diagnostic ID is auto generated ID by CSharp analyzer."
                },
                "TargetId": {
                    "type": "string",
                    "description": "Id of ReviewLine object where this diagnostic needs to be displayed"
                },
                "Text": {
                    "type": "string",
                    "description": "Auto generated system comment to be displayed under targeted line."
                },
                "Level": {
                    "$ref": "#/$defs/CodeDiagnosticLevel"
                },
                "HelpLinkUri": {
                    "type": "string"
                }
            },
            "required": [
                "TargetId",
                "Text",
                "Level"
            ],
            "description": "System comment object is to add system generated comment. It can be one of the 4 different types of system comments."
        },
        "NavigationItem": {
            "type": "object",
            "properties": {
                "Text": {
                    "type": "string"
                },
                "NavigationId": {
                    "type": "string"
                },
                "ChildItems": {
                    "type": "array",
                    "items": {
                        "$ref": "#/$defs/NavigationItem"
                    }
                },
                "Tags": {
                    "$ref": "#/$defs/RecordString"
                }
            },
            "required": [
                "Text",
                "NavigationId",
                "ChildItems",
                "Tags"
            ]
        },
        "LanguageIdMap": {
            "type": "object",
            "properties": {},
            "unevaluatedProperties": {
                "type": "string"
            },
            "description": "Maps a language-specific ID (key) to a TypeSpec ID (value).\nKey: Language-specific ID (e.g., 'en-US', 'fr-FR')\nValue: Cross-language TypeSpec ID"
        },
        "ReviewToken": {
            "type": "object",
            "properties": {
                "Kind": {
                    "$ref": "#/$defs/TokenKind"
                },
                "Value": {
                    "type": "string"
                },
                "NavigationDisplayName": {
                    "type": "string",
                    "description": "NavigationDisplayName is used to create a tree node in the navigation panel. Navigation nodes will be created only if token contains navigation display name."
                },
                "NavigateToId": {
                    "type": "string",
                    "description": "navigateToId should be set if the underlying token is required to be displayed as HREF to another type within the review.\nFor e.g. a param type which is class name in the same package"
                },
                "SkipDiff": {
                    "type": "boolean",
                    "default": false,
                    "description": "Set skipDiff to true if underlying token needs to be ignored from diff calculation. For e.g. package metadata or dependency versions \nare usually excluded when comparing two revisions to avoid reporting them as API changes"
                },
                "IsDeprecated": {
                    "type": "boolean",
                    "default": false,
                    "description": "This is set if API is marked as deprecated"
                },
                "HasSuffixSpace": {
                    "type": "boolean",
                    "default": true,
                    "description": "Set this to false if there is no suffix space required before next token. For e.g, punctuation right after method name"
                },
                "HasPrefixSpace": {
                    "type": "boolean",
                    "default": false,
                    "description": "Set this to true if there is a prefix space required before current token. For e.g, space before token for ="
                },
                "IsDocumentation": {
                    "type": "boolean",
                    "default": false,
                    "description": "Set isDocumentation to true if current token is part of documentation"
                },
                "RenderClasses": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "description": "Language specific style css class names. To render navigation icons, one of the following must be specified:\n\"namespace\", \"class\", \"method\", \"enum\". If NavigationDisplayName is specified, then this field should be set."
                }
            },
            "required": [
                "Kind",
                "Value"
            ],
            "description": "Token corresponds to each component within a code line. A separate token is required for keyword, punctuation, type name, text etc."
        },
        "CodeDiagnosticLevel": {
            "type": "number",
            "enum": [
                1,
                2,
                3,
                4
            ]
        },
        "RecordString": {
            "type": "object",
            "properties": {},
            "unevaluatedProperties": {
                "type": "string"
            }
        },
        "TokenKind": {
            "type": "number",
            "enum": [
                0,
                1,
                2,
                3,
                4,
                5,
                6,
                7,
                8
            ]
        }
    }
}

=== heaths/azure-sdk-tools/packages/python-packages/apiview-stub-generator/tests/azure_tests/token_files/azure-eventhub-checkpointstoreblob_python.json
{"PackageName": "azure-eventhub-checkpointstoreblob", "PackageVersion": "1.2.0", "ParserVersion": "0.3.28", "Language": "Python", "ReviewLines": [{"Tokens": [{"Kind": 0, "Value": "# Package is parsed using apiview-stub-generator(version:0.3.28), Python version: 3.10.12", "HasPrefixSpace": false, "HasSuffixSpace": false, "SkipDiff": true}], "IsContextEndLine": false, "LineId": "GLOBAL"}, {"Tokens": [], "IsContextEndLine": false}, {"Tokens": [], "IsContextEndLine": false}, {"Tokens": [{"Kind": 2, "Value": "namespace", "HasPrefixSpace": false, "HasSuffixSpace": true}, {"Kind": 0, "Value": "azure.eventhub.extensions.checkpointstoreblob", "HasPrefixSpace": false, "HasSuffixSpace": false, "SkipDiff": false, "NavigationDisplayName": "azure.eventhub.extensions.checkpointstoreblob", "RenderClasses": ["namespace"]}], "LineId": "azure.eventhub.extensions.checkpointstoreblob", "IsContextEndLine": false, "Children": [{"Tokens": [], "IsContextEndLine": false, "RelatedToLine": "azure.eventhub.extensions.checkpointstoreblob"}, {"Tokens": [{"Kind": 2, "Value": "class", "HasPrefixSpace": false, "HasSuffixSpace": true}, {"Kind": 0, "Value": "azure.eventhub.extensions.checkpointstoreblob.BlobCheckpointStore", "HasPrefixSpace": false, "HasSuffixSpace": false, "SkipDiff": false, "NavigationDisplayName": "BlobCheckpointStore", "RenderClasses": ["class"]}, {"Kind": 1, "Value": "(", "HasPrefixSpace": false, "HasSuffixSpace": false}, {"Kind": 3, "Value": "CheckpointStore", "HasPrefixSpace": false, "HasSuffixSpace": false}, {"Kind": 1, "Value": ")", "HasPrefixSpace": false, "HasSuffixSpace": false}, {"Kind": 1, "Value": ":", "HasPrefixSpace": false, "HasSuffixSpace": false}, {"Kind": 0, "Value": " ", "HasPrefixSpace": false, "HasSuffixSpace": false, "SkipDiff": false}, {"Kind": 2, "Value": "implements", "HasPrefixSpace": false, "HasSuffixSpace": true}, {"Kind": 3, "Value": "ContextManager", "HasPrefixSpace": false, "HasSuffixSpace": true}], "IsContextEndLine": false, "LineId": "azure.eventhub.extensions.checkpointstoreblob.BlobCheckpointStore", "Children": [{"Tokens": [], "IsContextEndLine": false, "RelatedToLine": "azure.eventhub.extensions.checkpointstoreblob.BlobCheckpointStore"}, {"Tokens": [{"Kind": 2, "Value": "def", "HasPrefixSpace": false, "HasSuffixSpace": true}, {"Kind": 0, "Value": "__init__", "HasPrefixSpace": false, "HasSuffixSpace": false, "SkipDiff": false, "RenderClasses": ["method"]}, {"Kind": 1, "Value": "(", "HasPrefixSpace": false, "HasSuffixSpace": false}], "IsContextEndLine": false, "LineId": "azure.eventhub.extensions.checkpointstoreblob.BlobCheckpointStore.__init__", "Children": [{"Tokens": [{"Kind": 0, "Value": "    self", "HasPrefixSpace": false, "HasSuffixSpace": false, "SkipDiff": false}, {"Kind": 1, "Value": ",", "HasPrefixSpace": false, "HasSuffixSpace": true}], "IsContextEndLine": false, "LineId": "azure.eventhub.extensions.checkpointstoreblob.BlobCheckpointStore.__init__.param(self)"}, {"Tokens": [{"Kind": 0, "Value": "    blob_account_url", "HasPrefixSpace": false, "HasSuffixSpace": false, "SkipDiff": false}, {"Kind": 1, "Value": ":", "HasPrefixSpace": false, "HasSuffixSpace": true}, {"Kind": 3, "Value": "str", "HasPrefixSpace": false, "HasSuffixSpace": false}, {"Kind": 1, "Value": ",", "HasPrefixSpace": false, "HasSuffixSpace": true}], "IsContextEndLine": false, "LineId": "azure.eventhub.extensions.checkpointstoreblob.BlobCheckpointStore.__init__.param(blob_account_url)"}, {"Tokens": [{"Kind": 0, "Value": "    container_name", "HasPrefixSpace": false, "HasSuffixSpace": false, "SkipDiff": false}, {"Kind": 1, "Value": ":", "HasPrefixSpace": false, "HasSuffixSpace": true}, {"Kind": 3, "Value": "str", "HasPrefixSpace": false, "HasSuffixSpace": false}, {"Kind": 1, "Value": ",", "HasPrefixSpace": false, "HasSuffixSpace": true}], "IsContextEndLine": false, "LineId": "azure.eventhub.extensions.checkpointstoreblob.BlobCheckpointStore.__init__.param(container_name)"}, {"Tokens": [{"Kind": 0, "Value": "    credential", "HasPrefixSpace": false, "HasSuffixSpace": false, "SkipDiff": false}, {"Kind": 1, "Value": ":", "HasPrefixSpace": false, "HasSuffixSpace": true}, {"Kind": 3, "Value": "Optional", "HasPrefixSpace": false, "HasSuffixSpace": false}, {"Kind": 1, "Value": "[", "HasPrefixSpace": false, "HasSuffixSpace": false}, {"Kind": 3, "Value": "Union", "HasPrefixSpace": false, "HasSuffixSpace": false}, {"Kind": 1, "Value": "[", "HasPrefixSpace": false, "HasSuffixSpace": false}, {"Kind": 3, "Value": "AzureNamedKeyCredential", "HasPrefixSpace": false, "HasSuffixSpace": false}, {"Kind": 1, "Value": ", ", "HasPrefixSpace": false, "HasSuffixSpace": false}, {"Kind": 3, "Value": "AzureSasCredential", "HasPrefixSpace": false, "HasSuffixSpace": false}, {"Kind": 1, "Value": ", ", "HasPrefixSpace": false, "HasSuffixSpace": false}, {"Kind": 3, "Value": "TokenCredential", "HasPrefixSpace": false, "HasSuffixSpace": false}, {"Kind": 1, "Value": "]]", "HasPrefixSpace": false, "HasSuffixSpace": false}, {"Kind": 1, "Value": "=", "HasPrefixSpace": true, "HasSuffixSpace": true}, {"Kind": 6, "Value": "None", "HasPrefixSpace": false, "HasSuffixSpace": false, "SkipDiff": false}, {"Kind": 1, "Value": ",", "HasPrefixSpace": false, "HasSuffixSpace": true}], "IsContextEndLine": false, "LineId": "azure.eventhub.extensions.checkpointstoreblob.BlobCheckpointStore.__init__.param(credential)"}, {"Tokens": [{"Kind": 0, "Value": "    *", "HasPrefixSpace": false, "HasSuffixSpace": false, "SkipDiff": false}, {"Kind": 1, "Value": ",", "HasPrefixSpace": false, "HasSuffixSpace": true}], "IsContextEndLine": false, "LineId": "azure.eventhub.extensions.checkpointstoreblob.BlobCheckpointStore.__init__.param(*)"}, {"Tokens": [{"Kind": 0, "Value": "    api_version", "HasPrefixSpace": false, "HasSuffixSpace": false, "SkipDiff": false}, {"Kind": 1, "Value": ":", "HasPrefixSpace": false, "HasSuffixSpace": true}, {"Kind": 3, "Value": "str", "HasPrefixSpace": false, "HasSuffixSpace": false}, {"Kind": 1, "Value": "=", "HasPrefixSpace": true, "HasSuffixSpace": true}, {"Kind": 5, "Value": "\"2019-07-07\"", "HasPrefixSpace": false, "HasSuffixSpace": false}, {"Kind": 1, "Value": ",", "HasPrefixSpace": false, "HasSuffixSpace": true}], "IsContextEndLine": false, "LineId": "azure.eventhub.extensions.checkpointstoreblob.BlobCheckpointStore.__init__.param(api_version)"}, {"Tokens": [{"Kind": 0, "Value": "    secondary_hostname", "HasPrefixSpace": false, "HasSuffixSpace": false, "SkipDiff": false}, {"Kind": 1, "Value": ":", "HasPrefixSpace": false, "HasSuffixSpace": true}, {"Kind": 3, "Value": "Optional", "HasPrefixSpace": false, "HasSuffixSpace": false}, {"Kind": 1, "Value": "[", "HasPrefixSpace": false, "HasSuffixSpace": false}, {"Kind": 3, "Value": "str", "HasPrefixSpace": false, "HasSuffixSpace": false}, {"Kind": 1, "Value": "]", "HasPrefixSpace": false, "HasSuffixSpace": false}, {"Kind": 1, "Value": "=", "HasPrefixSpace": true, "HasSuffixSpace": true}, {"Kind": 6, "Value": "...", "HasPrefixSpace": false, "HasSuffixSpace": false, "SkipDiff": false}, {"Kind": 1, "Value": ",", "HasPrefixSpace": false, "HasSuffixSpace": true}], "IsContextEndLine": false, "LineId": "azure.eventhub.extensions.checkpointstoreblob.BlobCheckpointStore.__init__.param(secondary_hostname)"}, {"Tokens": [{"Kind": 0, "Value": "    **kwargs", "HasPrefixSpace": false, "HasSuffixSpace": false, "SkipDiff": false}, {"Kind": 1, "Value": ":", "HasPrefixSpace": false, "HasSuffixSpace": true}, {"Kind": 3, "Value": "Any", "HasPrefixSpace": false, "HasSuffixSpace": false}], "IsContextEndLine": false, "LineId": "azure.eventhub.extensions.checkpointstoreblob.BlobCheckpointStore.__init__.param(kwargs)"}, {"Tokens": [{"Kind": 1, "Value": ")", "HasPrefixSpace": false, "HasSuffixSpace": false}, {"Kind": 1, "Value": "->", "HasPrefixSpace": true, "HasSuffixSpace": true}, {"Kind": 3, "Value": "None", "HasPrefixSpace": false, "HasSuffixSpace": false}, {"Kind": 1, "Value": ": ...", "HasPrefixSpace": false, "HasSuffixSpace": false}], "IsContextEndLine": false, "LineId": "azure.eventhub.extensions.checkpointstoreblob.BlobCheckpointStore.__init__.returntype"}]}, {"Tokens": [], "IsContextEndLine": true, "RelatedToLine": "azure.eventhub.extensions.checkpointstoreblob.BlobCheckpointStore.__init__"}, {"Tokens": [{"Kind": 2, "Value": "@classmethod", "HasPrefixSpace": false, "HasSuffixSpace": false}], "IsContextEndLine": false, "RelatedToLine": "azure.eventhub.extensions.checkpointstoreblob.BlobCheckpointStore.from_connection_string"}, {"Tokens": [{"Kind": 2, "Value": "def", "HasPrefixSpace": false, "HasSuffixSpace": true}, {"Kind": 0, "Value": "from_connection_string", "HasPrefixSpace": false, "HasSuffixSpace": false, "SkipDiff": false, "RenderClasses": ["method"]}, {"Kind": 1, "Value": "(", "HasPrefixSpace": false, "HasSuffixSpace": false}], "IsContextEndLine": false, "LineId": "azure.eventhub.extensions.checkpointstoreblob.BlobCheckpointStore.from_connection_string", "Children": [{"Tokens": [{"Kind": 0, "Value": "    cls", "HasPrefixSpace": false, "HasSuffixSpace": false, "SkipDiff": false}, {"Kind": 1, "Value": ",", "HasPrefixSpace": false, "HasSuffixSpace": true}], "IsContextEndLine": false, "LineId": "azure.eventhub.extensions.checkpointstoreblob.BlobCheckpointStore.from_connection_string.param(cls)"}, {"Tokens": [{"Kind": 0, "Value": "    conn_str", "HasPrefixSpace": false, "HasSuffixSpace": false, "SkipDiff": false}, {"Kind": 1, "Value": ":", "HasPrefixSpace": false, "HasSuffixSpace": true}, {"Kind": 3, "Value": "str", "HasPrefixSpace": false, "HasSuffixSpace": false}, {"Kind": 1, "Value": ",", "HasPrefixSpace": false, "HasSuffixSpace": true}], "IsContextEndLine": false, "LineId": "azure.eventhub.extensions.checkpointstoreblob.BlobCheckpointStore.from_connection_string.param(conn_str)"}, {"Tokens": [{"Kind": 0, "Value": "    container_name", "HasPrefixSpace": false, "HasSuffixSpace": false, "SkipDiff": false}, {"Kind": 1, "Value": ":", "HasPrefixSpace": false, "HasSuffixSpace": true}, {"Kind": 3, "Value": "str", "HasPrefixS
